# $ conda env create --file requirements.yml
# $ conda env update --file requirements.yml
name: otbenchmark
dependencies:
- python==3.9.1
- numpy==1.21.*
- matplotlib==3.4.2
- scipy==1.7.*
- openturns>=1.16
- jupyterlab==3.0.16
- nbconvert==6.1.0
- black==21.12b0
- pre-commit
- flake8
- pandas==1.3.*
- tqdm==4.61.2
- shapely==1.7.1
- pip:
  - black-nb==0.5.0

