version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Install package in a venv with setup
          command: |
            python3 -m venv venv
            source venv/bin/activate
            python setup.py install
            python tests/demo_axialbeam.py tmp
      - run:
          name: Create package source distribution
          command: |
            python3 -m venv venv
            source venv/bin/activate
            python setup.py sdist
      - run:
          name: Check style of Python Scripts with black
          command: |
            black --check otbenchmark --config pyproject.toml
      - run:
          name: Check style of Python Scripts with flake8
          command: |
            flake8 otbenchmark
      - run:
          name: Check style of Notebooks with black-nb
          command: |
            black-nb --check examples
            black-nb --check examples-on-server
      - run:
          name: Test
          command: ./.circleci/run_docker_linux.sh

workflows:
  main:
    jobs:
      - build-and-test

