name: Build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install
        shell: bash -l {0}
        run: pip install -r requirements.txt
      - name: Lint
        shell: bash -l {0}
        run: |
          black --check otbenchmark --config pyproject.toml
          flake8 otbenchmark
      - name: Test
        shell: bash -l {0}
        run: |
          pip install .
          cd tests && bash run-all.sh && cd -
      - name: Doc
        shell: bash -l {0}
        run: |
          sudo apt install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
          make html -C doc

